# Generated by Django 4.2.6 on 2023-10-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scheme_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Type', models.CharField(blank=True, choices=[('Disabilty', 'Disability'), ('Reservation', 'Reservation'), ('Profession', 'Profession'), ('State', 'State'), ('Insurance', 'Insurance'), ('General', 'General')], max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
