# Generated by Django 4.2.6 on 2023-11-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheme', '0004_remove_schemesdb_type1_remove_schemesdb_type2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemesdb',
            name='Type2',
            field=models.CharField(blank=True, choices=[('Disabilty', 'Disability'), ('Reservation', 'Reservation'), ('Profession', 'Profession'), ('State', 'State'), ('Insurance', 'Insurance'), ('General', 'General')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schemesdb',
            name='Type3',
            field=models.CharField(blank=True, choices=[('Disabilty', 'Disability'), ('Reservation', 'Reservation'), ('Profession', 'Profession'), ('State', 'State'), ('Insurance', 'Insurance'), ('General', 'General')], max_length=100, null=True),
        ),
    ]
